// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVVL1buJp3RFu5Dx3a56xIzV0IqTUU1Mo',
    appId: '1:489793983761:web:e01d4acaf4e1d157e4a8b0',
    messagingSenderId: '489793983761',
    projectId: 'app-carrito-de-compras-dae09',
    authDomain: 'app-carrito-de-compras-dae09.firebaseapp.com',
    storageBucket: 'app-carrito-de-compras-dae09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7fmK8Y0GEOJtxHD7PuX8uOLF6dJueJx0',
    appId: '1:489793983761:android:24f891f0e5f7cdc2e4a8b0',
    messagingSenderId: '489793983761',
    projectId: 'app-carrito-de-compras-dae09',
    storageBucket: 'app-carrito-de-compras-dae09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEfnnYl4ZL28l_xfOorJFv2NKYLI3FhcA',
    appId: '1:489793983761:ios:9bfa4948931e6e51e4a8b0',
    messagingSenderId: '489793983761',
    projectId: 'app-carrito-de-compras-dae09',
    storageBucket: 'app-carrito-de-compras-dae09.firebasestorage.app',
    iosBundleId: 'com.example.carritoCompras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEfnnYl4ZL28l_xfOorJFv2NKYLI3FhcA',
    appId: '1:489793983761:ios:9bfa4948931e6e51e4a8b0',
    messagingSenderId: '489793983761',
    projectId: 'app-carrito-de-compras-dae09',
    storageBucket: 'app-carrito-de-compras-dae09.firebasestorage.app',
    iosBundleId: 'com.example.carritoCompras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVVL1buJp3RFu5Dx3a56xIzV0IqTUU1Mo',
    appId: '1:489793983761:web:fafb00aa31938a21e4a8b0',
    messagingSenderId: '489793983761',
    projectId: 'app-carrito-de-compras-dae09',
    authDomain: 'app-carrito-de-compras-dae09.firebaseapp.com',
    storageBucket: 'app-carrito-de-compras-dae09.firebasestorage.app',
  );
}
